// Generated by gencpp from file remote_mutex_msgs/mutexSrv.msg
// DO NOT EDIT!


#ifndef REMOTE_MUTEX_MSGS_MESSAGE_MUTEXSRV_H
#define REMOTE_MUTEX_MSGS_MESSAGE_MUTEXSRV_H

#include <ros/service_traits.h>


#include <remote_mutex_msgs/mutexSrvRequest.h>
#include <remote_mutex_msgs/mutexSrvResponse.h>


namespace remote_mutex_msgs
{

struct mutexSrv
{

typedef mutexSrvRequest Request;
typedef mutexSrvResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct mutexSrv
} // namespace remote_mutex_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::remote_mutex_msgs::mutexSrv > {
  static const char* value()
  {
    return "76380b12c62c62b1c75ef04892016d2b";
  }

  static const char* value(const ::remote_mutex_msgs::mutexSrv&) { return value(); }
};

template<>
struct DataType< ::remote_mutex_msgs::mutexSrv > {
  static const char* value()
  {
    return "remote_mutex_msgs/mutexSrv";
  }

  static const char* value(const ::remote_mutex_msgs::mutexSrv&) { return value(); }
};


// service_traits::MD5Sum< ::remote_mutex_msgs::mutexSrvRequest> should match
// service_traits::MD5Sum< ::remote_mutex_msgs::mutexSrv >
template<>
struct MD5Sum< ::remote_mutex_msgs::mutexSrvRequest>
{
  static const char* value()
  {
    return MD5Sum< ::remote_mutex_msgs::mutexSrv >::value();
  }
  static const char* value(const ::remote_mutex_msgs::mutexSrvRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::remote_mutex_msgs::mutexSrvRequest> should match
// service_traits::DataType< ::remote_mutex_msgs::mutexSrv >
template<>
struct DataType< ::remote_mutex_msgs::mutexSrvRequest>
{
  static const char* value()
  {
    return DataType< ::remote_mutex_msgs::mutexSrv >::value();
  }
  static const char* value(const ::remote_mutex_msgs::mutexSrvRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::remote_mutex_msgs::mutexSrvResponse> should match
// service_traits::MD5Sum< ::remote_mutex_msgs::mutexSrv >
template<>
struct MD5Sum< ::remote_mutex_msgs::mutexSrvResponse>
{
  static const char* value()
  {
    return MD5Sum< ::remote_mutex_msgs::mutexSrv >::value();
  }
  static const char* value(const ::remote_mutex_msgs::mutexSrvResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::remote_mutex_msgs::mutexSrvResponse> should match
// service_traits::DataType< ::remote_mutex_msgs::mutexSrv >
template<>
struct DataType< ::remote_mutex_msgs::mutexSrvResponse>
{
  static const char* value()
  {
    return DataType< ::remote_mutex_msgs::mutexSrv >::value();
  }
  static const char* value(const ::remote_mutex_msgs::mutexSrvResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // REMOTE_MUTEX_MSGS_MESSAGE_MUTEXSRV_H
