(cl:in-package svaya_control-msg)
(cl:export '(JOINT_CNT-VAL
          JOINT_CNT
          JOINT_MAX_POS_LIMIT_NORMAL_MODE-VAL
          JOINT_MAX_POS_LIMIT_NORMAL_MODE
          JOINT_MIN_POS_LIMIT_NORMAL_MODE-VAL
          JOINT_MIN_POS_LIMIT_NORMAL_MODE
          JOINT_MAX_POS_LIMIT_REDUCED_MODE-VAL
          JOINT_MAX_POS_LIMIT_REDUCED_MODE
          JOINT_MIN_POS_LIMIT_REDUCED_MODE-VAL
          JOINT_MIN_POS_LIMIT_REDUCED_MODE
          JOINT_VEL_LIMIT_REDUCED_MODE-VAL
          JOINT_VEL_LIMIT_REDUCED_MODE
          JOINT_VEL_LIMIT_NORMAL_MODE-VAL
          JOINT_VEL_LIMIT_NORMAL_MODE
))