// Generated by gencpp from file remote_mutex_msgs/mutexSrvResponse.msg
// DO NOT EDIT!


#ifndef REMOTE_MUTEX_MSGS_MESSAGE_MUTEXSRVRESPONSE_H
#define REMOTE_MUTEX_MSGS_MESSAGE_MUTEXSRVRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace remote_mutex_msgs
{
template <class ContainerAllocator>
struct mutexSrvResponse_
{
  typedef mutexSrvResponse_<ContainerAllocator> Type;

  mutexSrvResponse_()
    : status(0)  {
    }
  mutexSrvResponse_(const ContainerAllocator& _alloc)
    : status(0)  {
  (void)_alloc;
    }



   typedef uint8_t _status_type;
  _status_type status;



// reducing the odds to have name collisions with Windows.h 
#if defined(_WIN32) && defined(STATUS_LOCKED)
  #undef STATUS_LOCKED
#endif
#if defined(_WIN32) && defined(STATUS_UNLOCKED)
  #undef STATUS_UNLOCKED
#endif

  enum {
    STATUS_LOCKED = 1u,
    STATUS_UNLOCKED = 0u,
  };


  typedef boost::shared_ptr< ::remote_mutex_msgs::mutexSrvResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::remote_mutex_msgs::mutexSrvResponse_<ContainerAllocator> const> ConstPtr;

}; // struct mutexSrvResponse_

typedef ::remote_mutex_msgs::mutexSrvResponse_<std::allocator<void> > mutexSrvResponse;

typedef boost::shared_ptr< ::remote_mutex_msgs::mutexSrvResponse > mutexSrvResponsePtr;
typedef boost::shared_ptr< ::remote_mutex_msgs::mutexSrvResponse const> mutexSrvResponseConstPtr;

// constants requiring out of line definition

   

   



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::remote_mutex_msgs::mutexSrvResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::remote_mutex_msgs::mutexSrvResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::remote_mutex_msgs::mutexSrvResponse_<ContainerAllocator1> & lhs, const ::remote_mutex_msgs::mutexSrvResponse_<ContainerAllocator2> & rhs)
{
  return lhs.status == rhs.status;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::remote_mutex_msgs::mutexSrvResponse_<ContainerAllocator1> & lhs, const ::remote_mutex_msgs::mutexSrvResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace remote_mutex_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::remote_mutex_msgs::mutexSrvResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::remote_mutex_msgs::mutexSrvResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::remote_mutex_msgs::mutexSrvResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::remote_mutex_msgs::mutexSrvResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::remote_mutex_msgs::mutexSrvResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::remote_mutex_msgs::mutexSrvResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::remote_mutex_msgs::mutexSrvResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "6d5878401ab4f108105f53837a17fdb3";
  }

  static const char* value(const ::remote_mutex_msgs::mutexSrvResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x6d5878401ab4f108ULL;
  static const uint64_t static_value2 = 0x105f53837a17fdb3ULL;
};

template<class ContainerAllocator>
struct DataType< ::remote_mutex_msgs::mutexSrvResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "remote_mutex_msgs/mutexSrvResponse";
  }

  static const char* value(const ::remote_mutex_msgs::mutexSrvResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::remote_mutex_msgs::mutexSrvResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint8 status\n"
"uint8 STATUS_LOCKED = 1\n"
"uint8 STATUS_UNLOCKED = 0 \n"
"\n"
;
  }

  static const char* value(const ::remote_mutex_msgs::mutexSrvResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::remote_mutex_msgs::mutexSrvResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.status);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct mutexSrvResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::remote_mutex_msgs::mutexSrvResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::remote_mutex_msgs::mutexSrvResponse_<ContainerAllocator>& v)
  {
    s << indent << "status: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.status);
  }
};

} // namespace message_operations
} // namespace ros

#endif // REMOTE_MUTEX_MSGS_MESSAGE_MUTEXSRVRESPONSE_H
