// Generated by gencpp from file svaya_control/master_id.msg
// DO NOT EDIT!


#ifndef SVAYA_CONTROL_MESSAGE_MASTER_ID_H
#define SVAYA_CONTROL_MESSAGE_MASTER_ID_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace svaya_control
{
template <class ContainerAllocator>
struct master_id_
{
  typedef master_id_<ContainerAllocator> Type;

  master_id_()
    : header()
    , master_id(0)
    , data(0)  {
    }
  master_id_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , master_id(0)
    , data(0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef int32_t _master_id_type;
  _master_id_type master_id;

   typedef int32_t _data_type;
  _data_type data;





  typedef boost::shared_ptr< ::svaya_control::master_id_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::svaya_control::master_id_<ContainerAllocator> const> ConstPtr;

}; // struct master_id_

typedef ::svaya_control::master_id_<std::allocator<void> > master_id;

typedef boost::shared_ptr< ::svaya_control::master_id > master_idPtr;
typedef boost::shared_ptr< ::svaya_control::master_id const> master_idConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::svaya_control::master_id_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::svaya_control::master_id_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::svaya_control::master_id_<ContainerAllocator1> & lhs, const ::svaya_control::master_id_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.master_id == rhs.master_id &&
    lhs.data == rhs.data;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::svaya_control::master_id_<ContainerAllocator1> & lhs, const ::svaya_control::master_id_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace svaya_control

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::svaya_control::master_id_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::svaya_control::master_id_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::svaya_control::master_id_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::svaya_control::master_id_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::svaya_control::master_id_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::svaya_control::master_id_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::svaya_control::master_id_<ContainerAllocator> >
{
  static const char* value()
  {
    return "31929dcb5d32f0ce0b1b86d1d23554be";
  }

  static const char* value(const ::svaya_control::master_id_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x31929dcb5d32f0ceULL;
  static const uint64_t static_value2 = 0x0b1b86d1d23554beULL;
};

template<class ContainerAllocator>
struct DataType< ::svaya_control::master_id_<ContainerAllocator> >
{
  static const char* value()
  {
    return "svaya_control/master_id";
  }

  static const char* value(const ::svaya_control::master_id_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::svaya_control::master_id_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"int32 master_id\n"
"\n"
"int32  data\n"
"\n"
"\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::svaya_control::master_id_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::svaya_control::master_id_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.master_id);
      stream.next(m.data);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct master_id_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::svaya_control::master_id_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::svaya_control::master_id_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "master_id: ";
    Printer<int32_t>::stream(s, indent + "  ", v.master_id);
    s << indent << "data: ";
    Printer<int32_t>::stream(s, indent + "  ", v.data);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SVAYA_CONTROL_MESSAGE_MASTER_ID_H
