# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from svaya_control/JointLimit.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class JointLimit(genpy.Message):
  _md5sum = "5401a4925cdae95fe53c373fe45e169d"
  _type = "svaya_control/JointLimit"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """uint8 joint_cnt
float64[] joint_max_pos_limit_normal_mode
float64[] joint_min_pos_limit_normal_mode
float64[] joint_max_pos_limit_reduced_mode
float64[] joint_min_pos_limit_reduced_mode
float64[] joint_vel_limit_reduced_mode
float64[] joint_vel_limit_normal_mode

"""
  __slots__ = ['joint_cnt','joint_max_pos_limit_normal_mode','joint_min_pos_limit_normal_mode','joint_max_pos_limit_reduced_mode','joint_min_pos_limit_reduced_mode','joint_vel_limit_reduced_mode','joint_vel_limit_normal_mode']
  _slot_types = ['uint8','float64[]','float64[]','float64[]','float64[]','float64[]','float64[]']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       joint_cnt,joint_max_pos_limit_normal_mode,joint_min_pos_limit_normal_mode,joint_max_pos_limit_reduced_mode,joint_min_pos_limit_reduced_mode,joint_vel_limit_reduced_mode,joint_vel_limit_normal_mode

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(JointLimit, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.joint_cnt is None:
        self.joint_cnt = 0
      if self.joint_max_pos_limit_normal_mode is None:
        self.joint_max_pos_limit_normal_mode = []
      if self.joint_min_pos_limit_normal_mode is None:
        self.joint_min_pos_limit_normal_mode = []
      if self.joint_max_pos_limit_reduced_mode is None:
        self.joint_max_pos_limit_reduced_mode = []
      if self.joint_min_pos_limit_reduced_mode is None:
        self.joint_min_pos_limit_reduced_mode = []
      if self.joint_vel_limit_reduced_mode is None:
        self.joint_vel_limit_reduced_mode = []
      if self.joint_vel_limit_normal_mode is None:
        self.joint_vel_limit_normal_mode = []
    else:
      self.joint_cnt = 0
      self.joint_max_pos_limit_normal_mode = []
      self.joint_min_pos_limit_normal_mode = []
      self.joint_max_pos_limit_reduced_mode = []
      self.joint_min_pos_limit_reduced_mode = []
      self.joint_vel_limit_reduced_mode = []
      self.joint_vel_limit_normal_mode = []

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self.joint_cnt
      buff.write(_get_struct_B().pack(_x))
      length = len(self.joint_max_pos_limit_normal_mode)
      buff.write(_struct_I.pack(length))
      pattern = '<%sd'%length
      buff.write(struct.Struct(pattern).pack(*self.joint_max_pos_limit_normal_mode))
      length = len(self.joint_min_pos_limit_normal_mode)
      buff.write(_struct_I.pack(length))
      pattern = '<%sd'%length
      buff.write(struct.Struct(pattern).pack(*self.joint_min_pos_limit_normal_mode))
      length = len(self.joint_max_pos_limit_reduced_mode)
      buff.write(_struct_I.pack(length))
      pattern = '<%sd'%length
      buff.write(struct.Struct(pattern).pack(*self.joint_max_pos_limit_reduced_mode))
      length = len(self.joint_min_pos_limit_reduced_mode)
      buff.write(_struct_I.pack(length))
      pattern = '<%sd'%length
      buff.write(struct.Struct(pattern).pack(*self.joint_min_pos_limit_reduced_mode))
      length = len(self.joint_vel_limit_reduced_mode)
      buff.write(_struct_I.pack(length))
      pattern = '<%sd'%length
      buff.write(struct.Struct(pattern).pack(*self.joint_vel_limit_reduced_mode))
      length = len(self.joint_vel_limit_normal_mode)
      buff.write(_struct_I.pack(length))
      pattern = '<%sd'%length
      buff.write(struct.Struct(pattern).pack(*self.joint_vel_limit_normal_mode))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      start = end
      end += 1
      (self.joint_cnt,) = _get_struct_B().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sd'%length
      start = end
      s = struct.Struct(pattern)
      end += s.size
      self.joint_max_pos_limit_normal_mode = s.unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sd'%length
      start = end
      s = struct.Struct(pattern)
      end += s.size
      self.joint_min_pos_limit_normal_mode = s.unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sd'%length
      start = end
      s = struct.Struct(pattern)
      end += s.size
      self.joint_max_pos_limit_reduced_mode = s.unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sd'%length
      start = end
      s = struct.Struct(pattern)
      end += s.size
      self.joint_min_pos_limit_reduced_mode = s.unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sd'%length
      start = end
      s = struct.Struct(pattern)
      end += s.size
      self.joint_vel_limit_reduced_mode = s.unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sd'%length
      start = end
      s = struct.Struct(pattern)
      end += s.size
      self.joint_vel_limit_normal_mode = s.unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self.joint_cnt
      buff.write(_get_struct_B().pack(_x))
      length = len(self.joint_max_pos_limit_normal_mode)
      buff.write(_struct_I.pack(length))
      pattern = '<%sd'%length
      buff.write(self.joint_max_pos_limit_normal_mode.tostring())
      length = len(self.joint_min_pos_limit_normal_mode)
      buff.write(_struct_I.pack(length))
      pattern = '<%sd'%length
      buff.write(self.joint_min_pos_limit_normal_mode.tostring())
      length = len(self.joint_max_pos_limit_reduced_mode)
      buff.write(_struct_I.pack(length))
      pattern = '<%sd'%length
      buff.write(self.joint_max_pos_limit_reduced_mode.tostring())
      length = len(self.joint_min_pos_limit_reduced_mode)
      buff.write(_struct_I.pack(length))
      pattern = '<%sd'%length
      buff.write(self.joint_min_pos_limit_reduced_mode.tostring())
      length = len(self.joint_vel_limit_reduced_mode)
      buff.write(_struct_I.pack(length))
      pattern = '<%sd'%length
      buff.write(self.joint_vel_limit_reduced_mode.tostring())
      length = len(self.joint_vel_limit_normal_mode)
      buff.write(_struct_I.pack(length))
      pattern = '<%sd'%length
      buff.write(self.joint_vel_limit_normal_mode.tostring())
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      start = end
      end += 1
      (self.joint_cnt,) = _get_struct_B().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sd'%length
      start = end
      s = struct.Struct(pattern)
      end += s.size
      self.joint_max_pos_limit_normal_mode = numpy.frombuffer(str[start:end], dtype=numpy.float64, count=length)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sd'%length
      start = end
      s = struct.Struct(pattern)
      end += s.size
      self.joint_min_pos_limit_normal_mode = numpy.frombuffer(str[start:end], dtype=numpy.float64, count=length)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sd'%length
      start = end
      s = struct.Struct(pattern)
      end += s.size
      self.joint_max_pos_limit_reduced_mode = numpy.frombuffer(str[start:end], dtype=numpy.float64, count=length)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sd'%length
      start = end
      s = struct.Struct(pattern)
      end += s.size
      self.joint_min_pos_limit_reduced_mode = numpy.frombuffer(str[start:end], dtype=numpy.float64, count=length)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sd'%length
      start = end
      s = struct.Struct(pattern)
      end += s.size
      self.joint_vel_limit_reduced_mode = numpy.frombuffer(str[start:end], dtype=numpy.float64, count=length)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sd'%length
      start = end
      s = struct.Struct(pattern)
      end += s.size
      self.joint_vel_limit_normal_mode = numpy.frombuffer(str[start:end], dtype=numpy.float64, count=length)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_B = None
def _get_struct_B():
    global _struct_B
    if _struct_B is None:
        _struct_B = struct.Struct("<B")
    return _struct_B
