# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from svaya_control/SafetyError.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class SafetyError(genpy.Message):
  _md5sum = "effb15012df92429b21d6d9d6f7df6c3"
  _type = "svaya_control/SafetyError"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """float64[] error_list
bool mode_of_operation
bool recovery_mode_flag
bool safety_limits_flag
int32[] status
"""
  __slots__ = ['error_list','mode_of_operation','recovery_mode_flag','safety_limits_flag','status']
  _slot_types = ['float64[]','bool','bool','bool','int32[]']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       error_list,mode_of_operation,recovery_mode_flag,safety_limits_flag,status

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(SafetyError, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.error_list is None:
        self.error_list = []
      if self.mode_of_operation is None:
        self.mode_of_operation = False
      if self.recovery_mode_flag is None:
        self.recovery_mode_flag = False
      if self.safety_limits_flag is None:
        self.safety_limits_flag = False
      if self.status is None:
        self.status = []
    else:
      self.error_list = []
      self.mode_of_operation = False
      self.recovery_mode_flag = False
      self.safety_limits_flag = False
      self.status = []

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      length = len(self.error_list)
      buff.write(_struct_I.pack(length))
      pattern = '<%sd'%length
      buff.write(struct.Struct(pattern).pack(*self.error_list))
      _x = self
      buff.write(_get_struct_3B().pack(_x.mode_of_operation, _x.recovery_mode_flag, _x.safety_limits_flag))
      length = len(self.status)
      buff.write(_struct_I.pack(length))
      pattern = '<%si'%length
      buff.write(struct.Struct(pattern).pack(*self.status))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sd'%length
      start = end
      s = struct.Struct(pattern)
      end += s.size
      self.error_list = s.unpack(str[start:end])
      _x = self
      start = end
      end += 3
      (_x.mode_of_operation, _x.recovery_mode_flag, _x.safety_limits_flag,) = _get_struct_3B().unpack(str[start:end])
      self.mode_of_operation = bool(self.mode_of_operation)
      self.recovery_mode_flag = bool(self.recovery_mode_flag)
      self.safety_limits_flag = bool(self.safety_limits_flag)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%si'%length
      start = end
      s = struct.Struct(pattern)
      end += s.size
      self.status = s.unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      length = len(self.error_list)
      buff.write(_struct_I.pack(length))
      pattern = '<%sd'%length
      buff.write(self.error_list.tostring())
      _x = self
      buff.write(_get_struct_3B().pack(_x.mode_of_operation, _x.recovery_mode_flag, _x.safety_limits_flag))
      length = len(self.status)
      buff.write(_struct_I.pack(length))
      pattern = '<%si'%length
      buff.write(self.status.tostring())
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sd'%length
      start = end
      s = struct.Struct(pattern)
      end += s.size
      self.error_list = numpy.frombuffer(str[start:end], dtype=numpy.float64, count=length)
      _x = self
      start = end
      end += 3
      (_x.mode_of_operation, _x.recovery_mode_flag, _x.safety_limits_flag,) = _get_struct_3B().unpack(str[start:end])
      self.mode_of_operation = bool(self.mode_of_operation)
      self.recovery_mode_flag = bool(self.recovery_mode_flag)
      self.safety_limits_flag = bool(self.safety_limits_flag)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%si'%length
      start = end
      s = struct.Struct(pattern)
      end += s.size
      self.status = numpy.frombuffer(str[start:end], dtype=numpy.int32, count=length)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_3B = None
def _get_struct_3B():
    global _struct_3B
    if _struct_3B is None:
        _struct_3B = struct.Struct("<3B")
    return _struct_3B
